version: "3.7"

volumes:
  db:
  node-modules:

secrets:
  auth-token:
    file: /data/containers/secrets/auth_token

services:
  console:
    image: console/console
    ports:
      - 8000:8000
    secrets:
      - auth-token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_LOG_LEVEL=DEBUG
      - FLASK_DEBUG=true
      - FLASK_SHANTY_OAUTH_CONFIG_URL=http://slipos.io:8000/api/oauth/config.json
      - FLASK_SHANTY_BASE_URL=http://slipos.io:8000/
      - AUTH_TOKEN_FILE=/run/secrets/auth_token
      - FLASK_DOCKER_SOCKET_PATH=/var/run/docker.sock
