version: "3.7"

volumes:
  db:

networks:
  shared:
    external:
      name: shared
  private:

services:
  console-back:
    image: console/back
    build:
      dockerfile: ./docker/console/Dockerfile
      target: python
      context: ./
    network_mode: host
    volumes:
      - ./back/api:/app/api:ro
      - ./docker/console/entrypoint.sh:/entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/sockets/docker.sock
      - db:/var/lib/console/
    ports:
      - 8008:8008
    environment:
      - FLASK_WPA_SOCKET_PATH=/var/run/sockets/wpa_supplicant
      - FLASK_NDS_SOCKET_PATH=/var/run/sockets/nds
      - FLASK_DOCKER_SOCKET_PATH=/var/run/sockets/docker.sock
      - FLASK_LOG_LEVEL=DEBUG
      - FLASK_DEBUG=true
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8008
      - FLASK_DB_PATH=/var/lib/console/db.sqlite3
      - FLASK_UUID_PATH=/var/lib/console/console.uuid
      - FLASK_CACHE_TYPE=flask_caching.contrib.uwsgicache.UWSGICache
      - FLASK_SHANTY_OAUTH_CONFIG_URL=http://website-back:8000/api/oauth/config.json
      - FLASK_SHANTY_BASE_URL=http://website-back:8000

  console-front:
    image: console/vue
    build:
      dockerfile: ./docker/console/Dockerfile
      target: node
      context: ./
    depends_on:
      - console-back
    network_mode: host
    volumes:
      - ./front/src:/front/src:ro
    ports:
      - 8080:8080
      - 8088:8888
    environment:
      - FLASK_HOST=localhost
      - FLASK_PORT=8008
      - VUE_HOST=0.0.0.0
      - VUE_PORT=8080

  console-tor:
    image: console/tor
    build:
      dockerfile: ./docker/tor/Dockerfile
      context: ./
